config/routes.rb
Rails.application.routes.draw do
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    get '/',                        to: 'static_pages#index'
    get :product_grid_left_sidebar, to: 'sample#product_grid_left_sidebar'
    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'
    resources :products,            only: :show
    get 'products/:id/large_pic',   to: 'products#show_large_pic'
    get 'products/:id/small_pic',   to: 'products#show_small_pic'
    resources :categories,          only: :show
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/potepan/product_decorator.rb
module Potepan::ProductDecorator
  def acquire_related_products
    return [] if taxon_ids.empty?

    Spree::Product.joins(:taxons)
                  .includes(master: %i(images default_price))
                  .where('spree_taxons.id IN (?) AND spree_products.id <> ?',
                         taxon_ids, id)
                  .distinct
                  .sample(Constants::DefaultSize::RELATED_IMAGES_LIMITATION)
  end

  Spree::Product.prepend self
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/potepan/categories_controller.rb
module Potepan
  class CategoriesController < ApplicationController
    def show
      @taxon    = Spree::Taxon.find(params[:id])
      @products = @taxon.products

      category_taxonomy = Spree::Taxonomy.find_by(name: 'Categories')
      category_taxons   = category_taxonomy.taxons unless category_taxonomy.nil?
      category_taxon    = category_taxons.find_by(name: 'Categories')
      if category_taxon.present?
        @large_categories = category_taxons.select { |t| t.parent_id == category_taxon.id }
        @small_categories = category_taxons.select { |t| t.parent_id != category_taxon.id }
      end
    end
  end
end

app/controllers/potepan/products_controller.rb
module Potepan
  class ProductsController < ApplicationController
    def show
      @product  ||= Spree::Product.find(params[:id])
      @variants   = Spree::Variant.where(product_id: @product.id)
      @images     = @product.images
      @related_products = @product.acquire_related_products

      respond_to do |format|
        format.html { render 'show' }
        format.js
      end
    end

    def show_large_pic
      @product  ||= Spree::Product.find(params[:id])
      @variant    = Spree::Variant.find(params[:variant_id])
      @images     = Spree::Image.where(viewable_id: @variant.id)
      render partial: 'image', collection: @images,
             locals: { picture_size: 'large' }
    end

    def show_small_pic
      @product  ||= Spree::Product.find(params[:id])
      @variant    = Spree::Variant.find(params[:variant_id])
      @images     = Spree::Image.where(viewable_id: @variant.id)
      render partial: 'image', collection: @images,
             locals: { picture_size: 'small' }
    end
  end
end

app/controllers/potepan/sample_controller.rb
class Potepan::SampleController < ApplicationController
  def index
  end

  def product_grid_left_sidebar
  end

  def product_list_left_sidebar
  end

  def single_product
  end

  def cart_page
  end

  def checkout_step_1
  end

  def checkout_step_2
  end

  def checkout_step_3
  end

  def checkout_complete
  end

  def blog_left_sidebar
  end

  def blog_right_sidebar
  end

  def blog_single_left_sidebar
  end

  def blog_single_right_sidebar
  end

  def about_us
  end

  def tokushoho
  end

  def privacy_policy
  end
end

app/controllers/potepan/static_pages_controller.rb
class Potepan::StaticPagesController < ApplicationController
  def index
    @products = Spree::Product.all.take(10)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # return full title of each page
  def full_title(page_title = '')
    base_title = 'BIGBAG Store'
    if page_title.blank?
      base_title
    else
      "#{page_title} - #{base_title}"
    end
  end
end

app/views/layouts/_footer.html.erb
<!-- FOOTER -->
<!-- COPY RIGHT -->
<div id="footer" class="copyRight clearfix">
  <div class="container">
    <div class="row">
      <div class="col-sm-7 col-xs-12">
        <p>&copy; 2016-<%= Time.current.year %> Copyright Potepan Store .</p>
      </div>
      <div class="col-sm-5 col-xs-12">
        <ul class="list-inline">
          <li><a href="#"><i class="fa fa-twitter"></i></a></li>
          <li><a href="#"><i class="fa fa-facebook"></i></a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_head.html.erb
<head>
  <!-- SITE TITTLE -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title><%= full_title(yield(:title)) %></title>
  <!-- PLUGINS CSS STYLE -->
  <%= stylesheet_link_tag "application", :media => "all" %>
  <!-- GOOGLE FONT -->
  <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Oxygen:400,300,700', :media => "all" %>
  <!-- CUSTOM CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
  <%= csrf_meta_tags %>
</head>

app/views/layouts/_header.html.erb
<!-- HEADER -->
<div class="header clearfix">
  <!-- TOPBAR -->
  <div class="topBar">
    <div class="container">
      <div class="row">
        <div class="col-md-6 hidden-sm hidden-xs">
          <ul class="list-inline">
            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
          </ul>
        </div>
        <div class="col-md-6 col-xs-12">
          <ul class="list-inline pull-right">
            <li class="dropdown searchBox">
              <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-search"></i></a>
              <ul class="dropdown-menu dropdown-menu-right">
                <form id="form01" action="product-grid-left-sidebar.html" method="post">
                <li>
                  <span class="input-group">
                    <input type="text" name="searchWord" class="form-control" placeholder="Search…" aria-describedby="basic-addon2">
                    <span onclick="FormSubmit();" class="input-group-addon addPointer" id="basic-addon2">検索</span>
                  </span>
                </li>
                </form>
              </ul>
            </li>
            <li class="dropdown">
              <a href="cart-page.html" class="dropdown-toggle" data-toggle="dropdown disabled"><i class="fa fa-shopping-cart"></i></a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <!-- NAVBAR -->
  <nav class="navbar navbar-main navbar-default" role="navigation">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to(image_tag("img/logo.png", :alt => ""), potepan_url, class: "navbar-brand") %>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to("Home", potepan_url) %></li>
          <li class="dropdown megaDropMenu active">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="300" data-close-others="true" aria-expanded="false">Shop</a>
            <ul class="dropdown-menu row">
              <li class="col-sm-3 col-xs-12">
                <ul class="list-unstyled">
                  <li>Products Grid View</li>
                  <li class="active"><a href="product_grid_left_sidebar.html">Products Sidebar Left</a></li>
                  <li><a href="product-grid-right-sidebar.html">Products Sidebar Right</a></li>
                  <li><a href="product-grid-3-col-filter.html">Products 3 Columns V1</a></li>
                  <li><a href="product-grid-3-col.html">Products 3 Columns V2</a></li>
                  <li><a href="product-grid-4-col.html">Products 4 Columns</a></li>
                </ul>
              </li>
              <li class="col-sm-3 col-xs-12">
                <ul class="list-unstyled">
                  <li>Products List View</li>
                  <li><a href="product_list_left_sidebar.html">Products Sidebar Left</a></li>
                  <li><a href="product-list-right-sidebar.html">Products Sidebar Right</a></li>
                  <li class="listHeading">Others</li>
                  <li><a href="single_product.html">Single Product</a></li>
                  <li><a href="cart_page.html">Cart Page</a></li>
                </ul>
              </li>
              <li class="col-sm-3 col-xs-12">
                <ul class="list-unstyled">
                  <li>Checkout</li>
                  <li><a href="checkout_step_1.html">Step 1 - Address</a></li>
                  <li><a href="checkout_step_2.html">Step 2 - Shipping</a></li>
                  <li><a href="checkout_step_3.html">Step 3 - Payment</a></li>
                  <li><a href="checkout_step_4.html">Step 4 - Payment</a></li>
                  <li><a href="checkout_complete.html">Order Complete</a></li>
                </ul>
              </li>
              <li class="col-sm-3 col-xs-12">
                <a href="#" class="menu-photo"><%= image_tag("img/menu-photo.jpg", :alt => "menu-img") %></a>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</div>

app/views/layouts/_modal.html.erb
<!-- LOGIN MODAL -->
<div class="modal fade login-modal" id="login" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title">ログイン</h3>
      </div>
      <div class="modal-body">
        <form action="login-" method="POST" role="form">
          <div class="form-group">
            <label for="login-email">メールアドレス</label>
            <input type="email" class="form-control" id="login-email">
          </div>
          <div class="form-group">
            <label for="login-password">パスワード</label>
            <input type="password" class="form-control" id="login-password">
          </div>
          <div class="checkbox">
            <label>
              <input type="checkbox"> 記憶しておく
            </label>
          </div>
          <button type="submit" class="btn btn-primary btn-block">ログイン</button>
          <a href="lost-password.html" class="btn btn-link btn-block">パスワードをお忘れの方</a>
        </form>
      </div>
    </div>
  </div>
</div>
<!-- SIGN UP MODAL -->
<div class="modal fade" id="signup" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title">新規登録</h3>
      </div>
      <div class="modal-body">
        <form action="" method="POST" role="form">
          <div class="form-group">
            <label for="signup-email">メールアドレス</label>
            <input type="email" class="form-control" id="signup-email">
          </div>
          <div class="form-group">
            <label for="signup-password">パスワード</label>
            <input type="password" class="form-control" id="signup-password">
          </div>
          <div class="form-group">
            <label for="signup-password-confirmation">パスワード（確認用）</label>
            <input type="password" class="form-control" id="signup-password-confirmation">
          </div>
          <button type="submit" class="btn btn-primary btn-block">登録する</button>
        </form>
      </div>
    </div>
  </div>
</div>
<!-- PORDUCT QUICK VIEW MODAL -->
<div class="modal fade quick-view" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <div class="media">
          <div class="media-left">
            <%= image_tag("products/quick-view/quick-view-01.jpg", :class => "media-object", :alt => "Image") %>
          </div>
          <div class="media-body">
            <h2>Old Skool Navy</h2>
            <h3>149円</h3>
            <p>Classic sneaker from Vans. Cotton canvas and suede upper. Textile lining with heel stabilizer and ankle support. Contrasting laces. Sits on a classic waffle rubber sole.</p>
            <span class="quick-drop">
              <select name="guiest_id3" id="guiest_id3" class="select-drop">
                <option value="0">S</option>
                <option value="1">M</option>
                <option value="2">L</option>
                <option value="3">XL</option>
              </select>
            </span>
            <span class="quick-drop resizeWidth">
              <select name="guiest_id4" id="guiest_id4" class="select-drop">
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
              </select>
            </span>
            <div class="btn-area">
              <a href="cart_page.html" class="btn btn-primary btn-block">カートへ入れる <i class="fa fa-angle-right" aria-hidden="true"></i></a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_partners.html.erb
<!-- LIGHT SECTION -->
<section class="lightSection clearfix">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="owl-carousel partnersLogoSlider">
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-01.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-02.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-03.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-04.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-05.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-01.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-02.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-03.png", :alt => "partner-img") %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <%= render 'layouts/head' %>
  <body>
    <div class="main-wrapper">
      <%= render 'layouts/header' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
    <%= render 'layouts/modal' %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/potepan/categories/_large_category.html.erb
<li>
  <a href="javascript:;" data-toggle="collapse" data-target="#<%= "category#{large_category.id}" %>"><%= large_category.name %><i class="fa fa-plus"></i></a>
  <ul id="<%= "category#{large_category.id}" %>" class="collapse collapseItem">
    <% has_small_category = false %>
    <% small_categories.each do |small_category| %>
      <% if large_category.id == small_category.parent_id %>
        <% has_small_category = true %>
        <li>
          <%= link_to potepan_category_path(small_category.id) do %>
            <i class="fa fa-caret-right" aria-hidden="true"></i> <%= small_category.name %> <span>(<%= small_category.products.count %>)</span>
          <% end %>
        </li>
      <% end %>
    <% end %>
    <% if !has_small_category %>
      <li>
        <%= link_to potepan_category_path(large_category.id) do %>
          <i class="fa fa-caret-right" aria-hidden="true"></i> <%= large_category.name %> <span>(<%= large_category.products.count %>)</span>
        <% end %>
      </li>
    <% end %>
  </ul>
</li>

app/views/potepan/categories/_product.html.erb
<div class="col-sm-4 col-xs-12">
  <%= link_to potepan_product_path(product.id) do %>
    <div class="productBox">
      <div class="productImage clearfix">
        <%= image_tag(product.display_image.attachment(:large)) %>
      </div>
      <div class="productCaption clearfix">
        <h5><%= product.name %></h5>
        <h3><%= product.display_price %></h3>
      </div>
    </div>
  <% end %>
</div>

app/views/potepan/categories/show.html.erb
<% provide(:title, "Category") %>
<!-- LIGHT SECTION -->
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2><%= @taxon.name %></h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li>
            <%= link_to("Home", potepan_url) %>
          </li>
          <li>
            <a href="#">shop</a>
          </li>
          <li class="active"><%= @taxon.name %></li>
        </ol>
      </div>
    </div>
  </div>
</section>
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix productsContent">
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-sm-4 col-xs-12 sideBar">
        <div class="panel panel-default">
          <div class="panel-heading">商品カテゴリー</div>
          <div class="panel-body">
            <div class="collapse navbar-collapse navbar-ex1-collapse navbar-side-collapse">
              <ul id="category" class="nav navbar-nav side-nav">
                <%= render partial: "large_category", collection: @large_categories, locals: {small_categories: @small_categories} %>
              </ul>
            </div>
          </div>
        </div>
        <div class="panel panel-default filterNormal">
          <div class="panel-heading">色から探す</div>
          <div class="panel-body">
            <ul class="list-unstyled">
              <li><a href="#">ブラック<span>(15)</span></a></li>
              <li><a href="#">ホワイト<span>(10)</span></a></li>
              <li><a href="#">レッド<span>(7)</span></a></li>
              <li><a href="#">ブルー<span>(12)</span></a></li>
              <li><a href="#">オレンジ<span>(12)</span></a></li>
            </ul>
          </div>
        </div>
        <div class="panel panel-default filterNormal">
          <div class="panel-heading">サイズから探す</div>
          <div class="panel-body">
            <ul class="list-unstyled clearfix">
              <li><a href="#">S<span>(15)</span></a></li>
              <li><a href="#">M<span>(10)</span></a></li>
              <li><a href="#">L<span>(7)</span></a></li>
              <li><a href="#">XL<span>(12)</span></a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="col-md-9 col-sm-8 col-xs-12">
        <div class="row filterArea">
          <div class="col-xs-6">
            <select name="guiest_id1" id="guiest_id1" class="select-drop">
              <option value="0">並び替え</option>
              <option value="1">人気順</option>
              <option value="2">安い順</option>
              <option value="3">新着順</option>
              <option value="3">高い順</option>
            </select>
          </div>
          <div class="col-xs-6">
            <div class="btn-group pull-right" role="group">
              <button type="button" class="btn btn-default active" onclick="window.location.href='product_grid_left_sidebar.html'"><i class="fa fa-th" aria-hidden="true"></i><span>Grid</span></button>
              <button type="button" class="btn btn-default" onclick="window.location.href='product_list_left_sidebar.html'"><i class="fa fa-th-list" aria-hidden="true"></i><span>List</span></button>
            </div>
          </div>
        </div>
        <div class="row">
          <%= render partial: "product", collection: @products %>
        </div>
      </div>
    </div>
  </div>
</section>
<%= render 'layouts/partners' %>

app/views/potepan/products/_image.html.erb
<% if picture_size == "large" %>
  <% if image_counter.zero? %>
    <div class="item active" data-thumb="0">
  <% else %>
    <div class="item" data-thumb=<%= "#{image_counter}" %> >
  <% end %>
    <%= image_tag(image.attachment(:large)) %>
  </div>
<% elsif picture_size == "small" %>
  <div data-target="#carousel" data-slide-to=<%= "#{image_counter}" %> class="thumb"><%= image_tag(image.attachment(:small)) %></div>
<% end %>

app/views/potepan/products/_related_product.html.erb
<div class="slide">
  <%= link_to potepan_product_path(related_product.id) do %>
    <div class="productImage clearfix">
      <%= image_tag(related_product.display_image.attachment(:large), :alt => "featured-product-img") %>
    </div>
    <div class="productCaption clearfix">
      <h5><%= related_product.name %></h5>
    </div>
  <% end %>
    <div>
      <h3><%= related_product.display_price %></h3>
    </div>
</div>

app/views/potepan/products/show.html.erb
<% provide(:title, "Single Product") %>
<!-- LIGHT SECTION -->
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2><%= @product.name %></h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li>
            <%= link_to("Home", potepan_url) %>
          </li>
          <li class="active"><%= @product.name %></li>
        </ol>
      </div>
    </div>
  </div>
</section>
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix">
  <div class="container">
    <div class="row singleProduct">
      <div class="col-xs-12">
        <div class="media">
          <div class="media-left productSlider">
            <div id="carousel" class="carousel slide" data-ride="carousel">
              <div id="picture_large" class="carousel-inner">
                <%= render partial: "image", collection: @images, locals: {picture_size: "large"} %>
              </div>
            </div>
            <div class="clearfix">
              <div id="thumbcarousel" class="carousel slide" data-interval="false">
                <div id="picture_small" class="carousel-inner">
                  <%= render partial: "image", collection: @images, locals: {picture_size: "small"} %>
                </div>
                <a class="left carousel-control" href="#thumbcarousel" role="button" data-slide="prev">
                  <span class="glyphicon glyphicon-chevron-left"></span>
                </a>
                <a class="right carousel-control" href="#thumbcarousel" role="button" data-slide="next">
                  <span class="glyphicon glyphicon-chevron-right"></span>
                </a>
              </div>
            </div>
          </div>
          <div class="media-body">
            <ul class="list-inline">
              <li>
                <%= link_to potepan_category_path(@product.taxons.first.id) do %>
                　<i class="fa fa-reply" aria-hidden="true"></i>一覧ページへ戻る
                <% end %>
              </li>
            </ul>
            <h2><%= @product.name %></h2>
            <h3><%= @product.display_price %></h3>
            <p><%= @product.description %></p>
            <% if @variants.count > 1 %>
              <span class="quick-drop">
                <select name="guiest_id3" id="guiest_id3" class="select-drop" data-remote="true">
                  <option value="0">-</option>
                  <option value="1">S</option>
                  <option value="2">M</option>
                  <option value="3">L</option>
                  <option value="4">XL</option>
                </select>
              </span>
              <span class="quick-drop">
                <select name="guiest_id4" id="guiest_id4" class="select-drop" data-remote="true">
                  <option value="0">-</option>
                  <option value="1">Red</option>
                  <option value="2">Blue</option>
                  <option value="3">Green</option>
                </select>
              </span>
            <% end %>
            <span class="quick-drop resizeWidth">
              <select name="guiest_id5" id="guiest_id5" class="select-drop">
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
              </select>
            </span>
            <div class="btn-area">
              <a href="cart_page.html" class="btn btn-primary btn-block">カートへ入れる<i class="fa fa-angle-right" aria-hidden="true"></i></a>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row productsContent">
      <div class="col-xs-12">
        <div class="page-header">
          <h4>関連商品</h4>
        </div>
      </div>
      <div class="col-xs-12">
        <div class="owl-carousel featuredProductsSlider">
          <%= render partial: "related_product", collection: @related_products %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/potepan/static_pages/_product.html.erb
<div class="slide">
  <div class="productImage clearfix">
    <%= link_to potepan_product_path(product.id) do %>
      <%= image_tag(product.display_image.attachment(:large), :alt => "featured-product-img") %>
    <% end %>
  </div>
  <div class="productCaption clearfix">
    <%= link_to potepan_product_path(product.id) do %>
      <h5><%= product.name %></h5>
    <% end %>
    <h3><%= product.display_price %></h3>
  </div>
</div>

app/views/potepan/static_pages/index.html.erb
<!-- BANNER -->
<div class="bannercontainer">
  <div class="fullscreenbanner-container">
    <div class="fullscreenbanner">
      <ul>
        <li>
          <%= image_tag("home/banner-slider/slider-bg.jpg", :alt => "slidebg1", data:{bgposition: "center center", bgfit: "cover" , bgrepeat: "no-repeat"}) %>
        </li>
      </ul>
    </div>
  </div>
</div>
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix">
  <div class="container">
    <div class="row featuredCollection">
      <div class="col-xs-12">
        <div class="page-header">
          <h4>人気カテゴリー</h4>
        </div>
      </div>
      <div class="col-sm-4 col-xs-12">
        <div class="thumbnail" onclick="location.href='/potepan/categories/7';">
          <div class="imageWrapper">
            <%= image_tag("home/featured-collection/featured-collection-01.jpg", :alt => "feature-collection-image") %>
            <div class="masking">
              <%= link_to "View T-Shirts", potepan_category_path(7), class: "btn viewBtn" %>
            </div>
          </div>
          <div class="caption">
            <h4>T-Shirts</h4>
          </div>
        </div>
      </div>
      <div class="col-sm-4 col-xs-12">
        <div class="thumbnail" onclick="location.href='/potepan/categories/3';">
          <div class="imageWrapper">
            <%= image_tag("home/featured-collection/featured-collection-02.jpg", :alt => "feature-collection-image") %>
            <div class="masking">
              <%= link_to "View Bags", potepan_category_path(3), class: "btn viewBtn" %>
            </div>
          </div>
          <div class="caption">
            <h4>Bags</h4>
          </div>
        </div>
      </div>
      <div class="col-sm-4 col-xs-12">
        <div class="thumbnail" onclick="location.href='/potepan/categories/4';">
          <div class="imageWrapper">
            <%= image_tag(Spree::Product.find(8).display_image.attachment(:large), :alt => "feature-collection-image") %>
            <div class="masking">
              <%= link_to "View Mugs", potepan_category_path(4), class: "btn viewBtn" %>
            </div>
          </div>
          <div class="caption">
            <h4>Mugs</h4>
          </div>
        </div>
      </div>
    </div>
    <div class="row featuredProducts">
      <div class="col-xs-12">
        <div class="page-header">
          <h4>人気商品</h4>
        </div>
      </div>
      <div class="col-xs-12">
        <div class="owl-carousel featuredProductsSlider">
          <%= render partial: "product", collection: @products %>
        </div>
      </div>
    </div>
  </div>
</section>
<%= render 'layouts/partners' %>